version: "3.9"
services:
  api:
    build: ./api
    expose:
      - "80"
    ports:
      - "80"
    environment:
      - STICKY_TODO_DB_HOST=sticky_todo_db
      - STICKY_TODO_DB_ID=admin
      - STICKY_TODO_DB_PASSWORD=admin
    networks:
      - "sticky-todo"
    deploy:
      mode: replicated
      replicas: 2

  db:
    build: ./db
    expose:
      - "27017"
    ports:
      - "27017"
    networks:
      - "sticky-todo"
    deploy:
      mode: replicated
      replicas: 1

networks:
  "sticky-todo":
