version: "3.9"
services:
  api:
    image: sticky-todo-api
    ports:
      - "8000:8000"
    environment:
      - STICKY_TODO_DB_HOST=sticky_todo_db
      - STICKY_TODO_DB_ID=admin
      - STICKY_TODO_DB_PASSWORD=admin
    volumes:
      - ./api:/usr/src/app
    networks:
      - "net"
    deploy:
      mode: replicated
      replicas: 2

  db:
    image: sticky-todo-db
    ports:
      - "27017:27017"
    networks:
      - "net"
    deploy:
      mode: replicated
      replicas: 1

networks:
  net:
    driver: overlay